
services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Listeners
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Controller quorum
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Logs y mínimos single-node
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9094:9094"

  create-topics:
    image: apache/kafka:3.9.0
    depends_on:
      - kafka
    entrypoint: ["bash","-lc"]
    command:
      - >
        set -euo pipefail;
        echo "Creando tópicos de prueba...";
        /opt/kafka/bin/kafka-topics.sh --create --topic users --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 || true;
        /opt/kafka/bin/kafka-topics.sh --create --topic orders --bootstrap-server kafka:9092 --partitions 2 --replication-factor 1 || true;
        /opt/kafka/bin/kafka-topics.sh --create --topic payments --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 || true;
        echo "Tópicos existentes:";
        /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server kafka:9092;
        echo "OK"